# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mapping Properties
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# Loader
neo_version=21.1.219
loader_version_range=[1,)

## Mod Properties
mod_id=steamcore
mod_name=Steam Core
mod_license=Steamcreate2 Mod Custom License
mod_version=1.0.6b
mod_group_id=com.steam.steamcore

# Metadata
logoFile="icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/steamcore"
authors="Dseelis"
description='''coremod for steamcore modpack.'''

# Dependencies

ftblibrary = 2101.1.30
ftbquests = 2101.1.21
