modLoader="javafml"
loaderVersion="[4,)"
license="Steamcreate2 Mod Custom License"

[[mixins]]
config="steamcore.mixins.json"

[[mods]]
modId="steamcore"
logoFile="icon.png"
version="1.1.4b"
description='''coremod for steamcore modpack.'''
displayName="Steamcore"
displayURL="https://www.curseforge.com/minecraft/mc-mods/steamcore"
issueTrackerURL="https://github.com/Dseelis/Steam-Core/issues"
authors="Dseelis"

[[dependencies.steamcore]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.227,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.steamcore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.steamcore]]
    modId="create"
    type="required"
    versionRange="[6.0.9,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.steamcore]]
    modId="cloth_config"
    type="required"
    versionRange="[15.0.140,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.steamcore]]
    modId="ftblibrary"
    type="required"
    versionRange="[2101.1.30,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.steamcore]]
    modId="ftbquests"
    type="required"
    versionRange="[2101.1.21,)"
    ordering="AFTER"
    side="BOTH"
